apiVersion: v1
kind: Namespace
metadata:
  name: ms-backend
  labels:
    name: ms-backend
---
apiVersion: v1
kind: Service
metadata:
  name: bangkok
  labels:
    name: bangkok
spec:
  selector:
    name: bangkok
  ports:
   - port: 8000
     targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bangkok
  namespace: micro-services
  labels:
    name: bangkok
spec:
  selector:
    matchLabels:
      name: bangkok
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: bangkok
    spec:
      containers:
        - name: bangkok
          image: vvamzy/front_gateway
          ports:
            - containerPort: 8000
              protocol: TCP
