apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    name: microservices
---
apiVersion: v1
kind: Service
metadata:
  name: munich
  labels:
    name: munich
spec:
  selector:
    name: munich
  ports:
   - port: 8000
     targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: munich
  namespace: microservices
  labels:
    name: munich
spec:
  selector:
    matchLabels:
      name: munich
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: munich
    spec:
      containers:
        - name: munich
          image: vvamzy/munich
          ports:
            - containerPort: 8000
              protocol: TCP
