apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    name: microservices
---
apiVersion: v1
kind: Service
metadata:
  name: nyc
  labels:
    name: nyc
spec:
  selector:
    name: nyc
  ports:
   - port: 9292
     targetPort: 9292
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyc
  namespace: microservices
  labels:
    name: nyc
spec:
  selector:
    matchLabels:
      name: nyc
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nyc
    spec:
      containers:
        - name: nyc
          image: vvamzy/nyc
