apiVersion: v1
kind: Namespace
metadata:
  name: ms-backend
  labels:
    name: ms-backend
---
apiVersion: v1
kind: Service
metadata:
  name: tokyo
  labels:
    name: tokyo
spec:
  selector:
    name: tokyo
  ports:
   - port: 3000
     targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokyo
  namespace: microservices
  labels:
    name: tokyo
spec:
  selector:
    matchLabels:
      name: tokyo
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: tokyo
    spec:
      containers:
        - name: tokyo
          image: vvamzy/tokyo
